// Ingredients
export const ADD_INGREDIENT_TO_FRIDGE = 'ADD_INGREDIENT_TO_FRIDGE';
export const ADD_INGREDIENT_TO_CART = 'ADD_INGREDIENT_TO_CART';
export const ADD_RECIPE = 'ADD_RECIPE';
export const CLEAR_RECIPE = 'CLEAR_RECIPE';
export const CLEAR_INGREDIENTS_IN_FRIDGE = 'CLEAR_INGREDIENTS_IN_FRIDGE';
export const UPDATE_INGREDIENT_IN_FRIDGE = 'UPDATE_INGREDIENT_IN_FRIDGE';
export const DELETE_INGREDIENT_IN_FRIDGE = 'DELETE_INGREDIENT_IN_FRIDGE';

export const ADD_INGREDIENT_TO_SCAN = 'ADD_INGREDIENT_TO_SCAN';
export const DELETE_INGREDIENT_TO_SCAN = 'DELETE_INGREDIENT_TO_SCAN';
export const CLEAR_INGREDIENTS_TO_SCAN = 'CLEAR_INGREDIENTS_TO_SCAN';

// Meal Plan
export const ADD_MEAL_PLAN = 'ADD_MEAL_PLAN'
export const DELETE_MEAL_PLAN = 'DELETE_MEAL_PLAN'
export const CLEAR_MEAL_PLAN = 'CLEAR_MEAL_PLAN'

// Recipes
export const ADD_FAVORITE_RECIPE = 'ADD_FAVORITE_RECIPE'
export const DELETE_FAVORITE_RECIPE = 'DELETE_FAVORITE_RECIPE'
export const CLEAR_FAVORITE_RECIPE = 'CLEAR_FAVORITE_RECIPE'

