export const ADD_INGREDIENT_TO_FRIDGE = 'ADD_INGREDIENT_TO_FRIDGE';
export const ADD_INGREDIENT_TO_CART = 'ADD_INGREDIENT_TO_CART';
export const ADD_RECIPE = 'ADD_RECIPE';
export const CLEAR_RECIPE = 'CLEAR_RECIPE';
export const CLEAR_INGREDIENTS_IN_FRIDGE = 'CLEAR_INGREDIENTS_IN_FRIDGE';
export const UPDATE_INGREDIENT_IN_FRIDGE = 'UPDATE_INGREDIENT_IN_FRIDGE';